apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::087885710532:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-11T11:27:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1201"
  uid: 3caf24fa-30f1-4e67-ac55-f98b61986512
